package nodos

const (
	// ACCOUNTS EVENTS
	ACCOUNT_CREATED        string = "ACCOUNT_CREATED"
	ACCOUNT_EMAIL_VERIFIED string = "ACCOUNT_EMAIL_VERIFIED"

	// PROFILES EVENTS
	PROFILE_ERROR string = "PROFILE_ERROR"
)
